graph TD
    matplotlib --> pillow
    matplotlib --> pyparsing
    matplotlib --> kiwisolver
    matplotlib --> numpy
    matplotlib --> cycler
    matplotlib --> python
    matplotlib --> contourpy
    matplotlib --> typing-extensions
    matplotlib --> pytz
    matplotlib --> wheel
    matplotlib --> packaging
    matplotlib --> pandas
    matplotlib --> six
    matplotlib --> fonttools
    matplotlib --> python-dateutil